import { StyleSheet } from 'react-native';

export const style = StyleSheet.create({
  mainContainer: {
    flex: 1,
    width: 'auto',
    backgroundColor: '#FFFFFF',
  },
  container: {
    marginHorizontal: 20,
    marginTop: 20,
  },
  questionText: {
    fontSize: 26,
    fontWeight: '500',
    marginBottom: 20,
    textAlign: 'center',
  },
  optionButton: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: 10,
    marginVertical: 5,
    borderRadius: 5,
    height: 50,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  optionText: {
    fontSize: 20,
  },
  optionTextBox: {
    display: 'flex',
    flexDirection: 'row',
    width: 310,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  optionLetterBox: {
    borderWidth: 1,
    height: 30,
    width: 30,
    borderRadius: 50,
    paddingTop: 2,
    alignItems: 'center',
    marginRight: 10,
    backgroundColor: '#fff',
  },
  resultText: {
    fontSize: 24,
    fontWeight: '600',
    marginTop: 20,
    textAlign: 'center',
  },
  buttonText: {
    fontSize: 22,
    fontWeight: '500',
    color: '#000',
  },
  buttonBox: {
    marginTop: 30,
    marginBottom: 20,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#000000',
    borderRadius: 10,
    width: 130,
    height: 40,
    padding: -5,
  },
  buttonDisable: {
    borderColor: '#aaa',
  },
  buttonNextQuestion: {
    height: 60,
    width: 150,
    flexDirection: 'row-reverse',
    gap: 10,
  },
  buttonNextQuestionBox: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
});

export const answer = StyleSheet.create({
  correctSelectAnswer: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#28C700',
    padding: 10,
    marginVertical: 5,
    borderRadius: 5,
    height: 50,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  correctAnswer: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderColor: '#28C700',
    borderWidth: 3,
    padding: 10,
    marginVertical: 5,
    borderRadius: 5,
    height: 50,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  wrongSelectAnswer: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: '#FF0000',
    padding: 10,
    marginVertical: 5,
    borderRadius: 5,
    height: 50,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  selectedOptionButton: {
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'row',
    padding: 10,
    marginVertical: 5,
    height: 50,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
});
